CREATE OR REPLACE PROCEDURE SANDBOX_QA.EDW.SP_STAGING_DIMWELLACTIVITYDAILY1(
DebugFlag BOOLEAN DEFAULT FALSE,
ProcessStartDateTime TIMESTAMP_NTZ DEFAULT NULL,
ProcessEndDateTime TIMESTAMP_NTZ DEFAULT NULL
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  VAR VARCHAR;
BEGIN
  Var := 'HELLO';
RETURN var;
END
$$;
